remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
title: Akhil Baby Sarada - Resume
description: Resume and professional History of Akhil Baby Sarada (akhilbhas)
show_downloads: false
google_analytics: false