remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
title: Akhil Baby Sarada
description: Embedded Software Engineer – Set Top Box | Embedded Linux | RDK Specialist
show_downloads: false
google_analytics: false