markdown:   kramdown
style:  kjhealy
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
title: Akhil Baby Sarada - Resume
description: REsume and proffessional History of Akhil Baby Sarada (akhilbhas)